name: Issue Trigger Example

on:
  issues:
    types: [opened]

jobs:
  issue:
    runs-on: ubuntu-latest  # This defines the environment the job will run on

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2 

      - name: Update Task or Trigger Action
        run: |
          echo "New issue opened: ${{ github.event.issue.title }}"
          # Using GitHub API to update issue, for example:
          curl -X PATCH https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
          -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          -d '{"state": "closed", "body": "This issue has been closed by the GitHub Actions workflow."}'
